### Load in NumPy

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [19]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.54228176, 0.56639292],
       [0.30751213, 0.17780132],
       [0.38062877, 0.30619095],
       [0.23980503, 0.77124494]])

In [25]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1, -1,  7],
       [ 7, -4,  4],
       [ 7, -2,  4]])

In [26]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [29]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a * 2

array([2, 4, 6, 8])

In [34]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [38]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [41]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.min(stats)

1

In [44]:
np.max(stats, axis=1)

array([3, 6])

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [50]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((4,2))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [51]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous


##### Load Data from File

In [54]:
filedata = np.genfromtxt('accrual_fraction_test.csv', delimiter=',')
# filedata = filedata.astype('int32')
print(filedata)

[[       nan        nan        nan        nan        nan        nan
         nan        nan        nan        nan]
 [       nan        nan        nan        nan 2.         0.9
  0.89673913 0.91666667 0.90410959 0.9       ]
 [       nan        nan        nan        nan 2.         0.07777778
  0.07608696 0.07777778 0.07671233 0.07777778]
 [       nan        nan        nan        nan 2.         0.94444444
  0.94535519 0.96111111 0.94794521 0.94444444]
 [       nan        nan        nan        nan 2.         0.31666667
  0.32065217 0.32777778 0.32328767 0.31666667]
 [       nan        nan        nan        nan 1.         0.00833333
  0.00821918 0.00833333 0.00821918 0.00833333]
 [       nan        nan        nan        nan 2.         0.76111111
  0.76086957 0.77777778 0.76712329 0.76111111]
 [       nan        nan        nan        nan 2.         0.25555556
  0.2568306  0.26111111 0.25753425 0.25555556]
 [       nan        nan        nan        nan 2.         0.91666667
  0.91847826 0.9388

##### Boolean Masking and Advanced Indexing

In [55]:
(~((filedata > 0.2) & (filedata < 0.6)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

### Broadcasting

In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8])

print(a.shape)
print(b.shape)
print(a+b)

(4,)
(4,)
[ 6  8 10 12]


In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([5])

print(a.shape)
print(b.shape)
print(a+b)

(4,)
(1,)
[6 7 8 9]


In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,])

print(a.shape)
print(b.shape)
print(a+b)

(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([[5]])

print(a.shape)
print(b.shape)
print(a+b)

(4,)
(1, 1)
[[6 7 8 9]]


In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([[5],[5]])

print(a.shape)
print(b.shape)
print(a+b)

(4,)
(2, 1)
[[6 7 8 9]
 [6 7 8 9]]


In [ ]:
a = np.random.random((2,3))
b = np.random.random((3,2))

print(a.shape)
print(b.shape)
print(a+b)

(2, 3)
(3, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
a = np.random.random((3,3))
b = np.random.random((3,1))

print(a.shape)
print(b.shape)
print(a+b)

(3, 3)
(3, 1)
[[0.84987353 1.02641999 0.36264456]
 [1.15457339 1.09191906 1.37404699]
 [1.24198455 1.30536591 1.04821064]]
